# Generated by Django 2.1 on 2019-08-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSold', models.DateField()),
                ('numberSold', models.IntegerField()),
                ('productSold', models.TextField()),
                ('payoutValue', models.FloatField()),
            ],
        ),
    ]
