# Generated by Django 2.1 on 2019-08-19 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissiontracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='dateSold',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='payoutValue',
        ),
    ]
